#!/bin/bash

bin="cache/void-packages/xbps-src"

if [ ! -e "$bin" ]; then
	echo "ERROR: $bin doesn't exist yet."
	echo "You'll need to run overlay.sh first!"
	exit 1
fi

cd cache/void-packages
./xbps-src $*
